version: '3.3'
services:
  backend:
    volumes:
      - '${PWD}:/backend'
    ports:
      - '8001:8000'
    build:
      context: ./backend/
      dockerfile: Dockerfile
  frontend:
    volumes:
      - '${PWD}:/frontend'
      - /frontend/node_modules
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend/
      dockerfile: Dockerfile
