version: '3.3'
services:
  backend:
    image: backend:dev
    volumes:
      - '${PWD}/backend:/backend'
    ports:
      - '8001:8000'
    build:
      context: ./backend/
      dockerfile: Dockerfile
  frontend:
    image: 'frontend:dev'
    stdin_open: true
    volumes:
      - '${PWD}/frontend:/frontend'
      - /frontend/node_modules
    ports:
      - '3001:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend/
      dockerfile: Dockerfile
